spring:
  application:
    name: delivery-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/delivery
    username: delivery
    password: delivery

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: delivery-backend
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.github.zenkolespadon.delivery.*
        spring.json.value.default.type: com.github.zenkolespadon.delivery.event.GpsEvent

  data:
    redis:
      host: localhost
      port: 6379

delivery:
  kafka:
    topics:
      gps-events: gps-events
      delivery-events: delivery-events
      driver-events: driver-events
      eta-updated: eta-updated
      geofence-events: geofence-events
      delivery-alerts: delivery-alerts
      dead-letter-events: dead-letter-events

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  cors:
    allowed-origins: http://localhost:3000

  simulation:
    enabled: true
    driver-count: 10
    publish-interval-ms: 2000
    center-lat: 43.6045
    center-lng: 1.4440
    spawn-radius-km: 5

  routing:
    osrm-enabled: true
    osrm-base-url: http://localhost:5000
    request-timeout-ms: 1500

  websocket:
    drivers-live-broadcast-interval-ms: 2000


server:
  port: 8080
